config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'study_items#index'
  
  resources :study_categories

  resources :study_items do
    post 'concluded', on: :member
    post 'unconcluded', on: :member
  end
  
  resources :study_items do
    resources :study_comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/study_category.rb
class StudyCategory < ApplicationRecord
    validates :title, presence: { message: 'Não pode estar em branco.'}
end

app/models/study_comment.rb
class StudyComment < ApplicationRecord
  belongs_to :study_item
end

app/models/study_item.rb
class StudyItem < ApplicationRecord
    has_many :study_comments, dependent: :destroy
    validates :title, presence: { message: 'Não pode estar em branco.'}
    scope :search, ->(query) {where('title like ? OR category_id like ?',
    "%#{query}%", "%#{query}%")}

    def finalized?
        finalized_at.present?
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/study_categories_controller.rb
class StudyCategoriesController < ApplicationController
  before_action :set_study_category, only: [:show, :edit, :update, :destroy]

  def edit; end
  def show; end

  def index
    @study_categories = StudyCategory.all
  end

  def new
    @study_category = StudyCategory.new
  end

  def create
    @study_category = StudyCategory.new(study_category_params)
      if @study_category.save
        redirect_to @study_category
      else
        render :new
      end
  end

  def update
      if @study_category.update(study_category_params)
        redirect_to @study_category
      else
        render :edit
      end
  end

  def destroy
    @study_category.destroy
    redirect_to study_categories_url
  end

  private
    def set_study_category
      @study_category = StudyCategory.find(params[:id])
    end

    def study_category_params
      params.require(:study_category).permit(:title)
    end
end

app/controllers/study_comments_controller.rb
class StudyCommentsController < ApplicationController
  
  def create
    @study_item = StudyItem.find(params[:study_item_id])
    @study_comment = @study_item.study_comments.create(study_comment_params)
    redirect_to study_item_path(@study_item)
  end
    

  def destroy
    @study_item = StudyItem.find(params[:study_item_id])
    @study_comment = @study_item.study_comments.find(params[:id])
    @study_comment.destroy
    redirect_to study_item_path(@study_item)
  end

  private
    def study_comment_params
      params.require(:study_comment).permit(:commenter, :body)
    end

end

app/controllers/study_items_controller.rb
class StudyItemsController < ApplicationController
  before_action :set_study_item, only: %i[show edit update destroy concluded unconcluded]

  def show;end
  def edit;end

  def index
    if params[:search]
      @study_items = StudyItem.search(params[:search])
    else
      @study_items = StudyItem.all
    end
  end

  def new
    @study_item = StudyItem.new
  end

  def create
    @study_item = StudyItem.new(study_item_params)
      if @study_item.save
        redirect_to @study_item
      else
        render :new 
      end
  end

  def update
      if @study_item.update(study_item_params)
        redirect_to @study_item
      else
        render :edit
      end
  end

  def destroy
    @study_item.destroy
    redirect_to study_items_url
  end

  def concluded
    @study_item.update(finalized_at: Date.current)
    @study_item.status = '✔'
    @study_item.save
    redirect_to study_items_path
  end

  def unconcluded
    @study_item.update(finalized_at:'')
    @study_item.status = '❌'
    @study_item.save
    redirect_to study_items_path
  end

  private
    def set_study_item
      @study_item = StudyItem.find(params[:id])
    end

    def study_item_params
      params.require(:study_item).permit(:title, :category_id, :description, :deadline, :status, :item_kind)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diário de estudos - QSD GIRLS 2020</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">

    <a class="navbar-brand" href="../study_items">HOME</a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to 'Novo tópico', new_study_item_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
      <%= link_to 'Categorias', study_categories_path, class: "nav-link" %>
      </li>

      </ul>

      <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logado como: <strong><%= current_user.email %></strong>.
  <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

    </div>
  </div>
</nav>
</center>

<div class="container">
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
  <%= yield %>
</div>

<footer>
  <div class="container">
    <center style="color:CadetBlue;">ANA FELIZATTI - QSD GIRLS <%= Time.now.year %></center>
  </div>
</footer>

  </body>

</html>

app/views/study_categories/_form.html.erb
<% if study_category.errors.any? %>
<div id="error_explanation">
<p style ="color:Red;">Atenção! Ação não concluída:<p>
    <% study_category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <hr>
    <% end %>
</div>
<% end %>

<%= form_with(model: study_category, local: true) do |form| %>

  <div class="field">
    <%= form.label "Categoria" %>
    <br>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <br>
    <%= form.submit 'Salvar' %>
    <hr>
  </div>


<% end %>

app/views/study_categories/edit.html.erb
<hr>
<strong>
  <p style ="color:CadetBlue;"> Alterar categoria de estudo  </p>
</strong>
<hr>

<br>
<%= render 'form', study_category: @study_category %>
<hr>
<%= link_to 'Visualizar', @study_category %> |
<%= link_to 'Página inicial', study_categories_path %>

app/views/study_categories/index.html.erb
<p id="notice"><%= notice %></p>

<hr>
<strong>
  <p style ="color:CadetBlue;"> Categorias de estudo  </p>
</strong>
<hr>

<hr>

<center><table width="50%">
  <thead>
    <tr>
      <th>CATEGORIA</th>
      <td></td>
      <td></td>
      <td></td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @study_categories.each do |study_category| %>
      <tr>
        <td><%= link_to study_category.title.upcase, study_category %></td>
        <td></td>
        <td><%= link_to 'Alterar', edit_study_category_path(study_category) %></td>
        <td><%= link_to 'Deletar', study_category, method: :delete, data: { confirm: 'Você está certo disso?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<hr>
<strong><%= link_to 'Adicionar nova categoria', new_study_category_path %></strong>
</center>

app/views/study_categories/new.html.erb
<hr>
<strong>
  <p style ="color:CadetBlue;"> Nova categoria de estudo  </p>
</strong>
<hr>

<%= render 'form', study_category: @study_category %>
<br>
<%= link_to 'Voltar para CATEGORIAS', study_categories_path %>

app/views/study_categories/show.html.erb
<hr>
<strong>
  <p style ="color:CadetBlue;"> Detalhes de categoria de estudo  </p>
</strong>
<hr>

<p>
  <strong>Title:</strong>
  <%= @study_category.title %>
</p>

<%= link_to 'Editar', edit_study_category_path(@study_category) %> |
<%= link_to 'Voltar', study_categories_path %>

app/views/study_comments/_form.html.erb
<%= form_with(model: [ @study_item, @study_item.study_comments.build ], local: true) do |form| %>
    
  <p>
      <%= form.label 'Usuário' %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label 'Comentário' %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit 'Adicionar comentário' %>
    </p>

<% end %>

app/views/study_comments/_study_comment.html.erb
<p>
<strong>Usuário:</strong>
<%= study_comment.commenter %>
</p>

<p>
<strong>Comentário:</strong>
<%= study_comment.body %>
</p>

<p>
  <%= link_to "Deletar comentário de " + study_comment.commenter, [study_comment.study_item, study_comment],
               method: :delete,
               data: { confirm: 'Você tem certeza?' } %>
</p>

<hr>

app/views/study_items/_form.html.erb
<% if study_item.errors.any? %>
<div id="error_explanation">
<p style ="color:Red;">Atenção! Ação não concluída:<p>
    <% study_item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <hr>
    <% end %>
</div>
<% end %>

<%= form_with(model: study_item, local: true) do |form| %>

  <div class="field">
    <%= form.label "Item" %>
    <br>
    <%= form.text_field :title, :size=>"28" %>
  </div>
  <br>

  <div class="control-group">
    <%= form.label "Tipo de item de estudo", class: 'control-label'  %>
    <br>
    <%= select("study_item","item_kind",['🎦','📘','📑','💻','🔊','Outro'],  {:prompt => 'Selecione um ícone'}) %>
    <br>
  </div>
    
  <br>
  
  <div class="control-group">
    <%= form.label "Categorias",class: 'control-label'  %>
    <div class="controls">
      <%= collection_select( :study_item, :category_id, StudyCategory.all, :title, :title, {}, { :multiple => false} ) %>
    </div>
  </div>
  
  <br>
  <div class="field">
    <%= form.label "Prazo: dd/mm/aaa" %>
    </br>
    <%= form.text_field :deadline %>
    <br>
  </div>
  <br>
  <div class="field">
    <%= form.label "Descrição" %>
    <br>
    <%= form.text_area :description, :size=>"30" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit 'Salvar' %>
    <hr>
  </div>


<% end %>

app/views/study_items/edit.html.erb
<hr>
<strong>
  <p style ="color:CadetBlue;"> Alterar item de estudo  </p>
</strong>
<hr>

<%= render 'form', study_item: @study_item %>

<%= link_to 'Visualizar', @study_item %> |
<%= link_to 'Página inicial', study_items_path %>
</center>

app/views/study_items/index.html.erb
<strong>
<p id="notice"><%= notice %></p>
</strong>

<hr>
<center>
  <h2 style ="color:DarkSlateGray;"> Diário de estudos </h2>
  <p style ="color:CadetBlue;"> Seja bem vindo!  </p>
</center>

<hr>
<p> <i> Esta aplicação é um diário de estudos. Através dela é possível cadastrar tópicos de estudo com comentários
e definir suas categorias, além de atribuir prazos de estudo para monitorar seu progresso! </i> </p>
<hr>
<br>

<center> <h6> MEUS ITEMS</h6> </center>
<br>
<div style="text-align: right;"><%= form_tag(study_items_path, method: :get) do %>
  <%= text_field_tag 'search', nil, placeholder: 'Item ou categoria' %>
  <%= submit_tag 'Pesquisar' %>
<% end %></div>
<hr>

<table width="90%">
  <thead>
    <tr>
      <th>Item</th>
      <td></td>
      <th>Tipo</th>
      <td></td>
      <th>Categoria</th>
      <td></td>
      <th>Descrição</th>
      <td></td>
      <th>Prazo</th>
      <td></td>
      <th>Status</th>
      <td></td>
      <th><i><center> Alterar status </center></i></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @study_items.each do |study_item| %>
      <tr>
        <td><%= link_to study_item.title.upcase, study_item %></td>
        <td></td>
        <td><%= study_item.item_kind %></td>
        <td></td>
        <td><%= study_item.category_id %></td>
        <td></td>
        <td><%= study_item.description %></td>
        <td></td>
        <td><%= study_item.deadline.strftime("%d/%m/%Y") %></td>
        <td></td>
        <td><%= study_item.status %></td>
        <td></td>
        <td><strong><%= link_to 'Concluído', concluded_study_item_path(study_item), method: :post %></td></strong>
        <td><strong><%= link_to 'Pendente', unconcluded_study_item_path(study_item), method: :post %></td></strong>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= link_to 'Editar', edit_study_item_path(study_item) %></td>
        <td></td>
        <td><%= link_to 'Deletar', study_item, method: :delete, data: { confirm: 'Você está certo disso?' } %></td>
        <td></td>

        </tr>
    <% end %>
  </tbody>
</table>

<br>
<hr>
<center><%= link_to 'Cadastrar um novo item', new_study_item_path %></center>
<hr>

app/views/study_items/new.html.erb
<hr>
<h5 style="color:CadetBlue;">Cadastrar um novo tópico de estudo</h5>
<hr>

<%= render 'form', study_item: @study_item %>

<%= link_to 'CADASTRAR OUTRA CATEGORIA', study_categories_path %>
<hr>
<%= link_to 'HOME', study_items_path %>

app/views/study_items/show.html.erb
<hr>
<strong>
  <p style ="color:CadetBlue;"> Detalhes de item de estudo  </p>
</strong>
<hr>

<p>
  <strong>Item de estudo :</strong>
  <%= @study_item.title %>
</p>
<p>

<p>
  <strong>Tipo :</strong>
  <%= @study_item.item_kind %>
</p>
<p>

  <strong>Categoria :</strong>
  <%= @study_item.category_id %>
</p>
<p>
  <strong>Prazo :</strong>
  <%= @study_item.deadline.strftime("%d/%m/%y") %>
</p>

<p>
  <strong>Descrição :</strong>
  <%= @study_item.description %>
</p>
<p>
  <strong>Status :</strong>
  <%= @study_item.status %>
</p>
<hr>
<br>
<% if @study_item.finalized? && @study_item.status = '✔'%>
<p>Finalizada em <%= @study_item.finalized_at.strftime('%d/%m/%y') %> </p>
<% elsif @study_item.status = '❌'%>
<%= link_to 'Marcar como feito', concluded_study_item_path(@study_item), method: :post %> </center></strong>
<% end %> 
<br>
<br>
<% if @study_item.deadline < Date.current && @study_item.status == '❌' %>
<center><h6 style ="color:red;"> ATENÇÃO: ITEM EM EM ATRASO </h6></center>
<% end %> 
<br>

<strong><center><%= link_to 'Alterar item', edit_study_item_path(@study_item) %> |
<%= link_to 'Página inicial', study_items_path %></center></strong>

<hr>
<strong>
  <center> <h4 style ="color:CadetBlue;"> Comentários  </h4></center>
</strong>
<hr>
<%= render @study_item.study_comments %>


<center><i><p>Adicione um comentário</p></i>
<%= render 'study_comments/form' %>
<hr></center>

<center><%= link_to 'HOME', study_items_path %></center></strong></center>